buffer:
  base_points: 0.0003
  max_buffer: 0.0008
  min_buffer: 0.0002
  volatility_scalar: 0.25
context:
  correlation_instruments: []
  correlation_weight: 0.0
  typical_adr: 0.0035
display_name: Euro FX
or:
  base_minutes: 20
  high_vol_threshold: 0.85
  low_vol_threshold: 0.35
  max_minutes: 30
  min_minutes: 20
session_end: '14:00'
session_start: 07:20
sizing:
  preferred_contract: M6E
  scale_to_mini_at_r: 6.0
stop:
  atr_cap_mult: 1.0
  max_risk_r: 1.5999999999999999
  min_points: 0.0006
symbol: 6E
targets:
  runner_r: 4.5
  runner_trail_mode: structure
  t1_fraction: 0.6
  t1_r: 1.3
  t2_fraction: 0.4
  t2_r: 3.0
tick_size: 5.0e-05
tick_value: 6.25
tick_value_micro: 1.25
time_stop:
  enabled: false
  min_progress_r: 0.4
  minutes: 60
validity:
  max_width_norm: 7.0
  max_width_points: 0.004
  min_width_norm: 0.22
  min_width_points: 0.0003
volume:
  cum_ratio_max: 5.0
  cum_ratio_min: 0.5
  min_drive_energy: 0.25
  spike_threshold_mult: 4.0
yahoo_symbol: 6E=F
