buffer:
  base_points: 2.0
  max_buffer: 4.0
  min_buffer: 1.5
  volatility_scalar: 0.3
context:
  correlation_instruments:
  - ES
  correlation_weight: 0.5
  typical_adr: 180.0
display_name: E-mini NASDAQ 100
or:
  base_minutes: 15
  high_vol_threshold: 0.85
  low_vol_threshold: 0.35
  max_minutes: 30
  min_minutes: 15
session_end: '15:00'
session_start: 08:30
sizing:
  preferred_contract: MNQ
  scale_to_mini_at_r: 5.0
stop:
  atr_cap_mult: 1.0
  max_risk_r: 1.5999999999999999
  min_points: 12.0
symbol: NQ
targets:
  runner_r: 4.5
  runner_trail_mode: structure
  t1_fraction: 0.6
  t1_r: 1.3
  t2_fraction: 0.4
  t2_r: 3.0
tick_size: 0.25
tick_value: 5.0
tick_value_micro: 0.5
time_stop:
  enabled: false
  min_progress_r: 0.4
  minutes: 60
validity:
  max_width_norm: 8.0
  max_width_points: 120.0
  min_width_norm: 0.18
  min_width_points: 8.0
volume:
  cum_ratio_max: 5.0
  cum_ratio_min: 0.5
  min_drive_energy: 0.25
  spike_threshold_mult: 4.0
yahoo_symbol: NQ=F
